name: CI/CD - Java Maven App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Cache Maven Dependencies
      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build the JAR File
      - name: Build and Run Tests
        run: |
          mvn clean package
          mvn test

      # ✅ Upload JAR to GitHub Packages (Maven repository)
      - name: Upload JAR to GitHub Packages
        run: |
          # GitHub Packages Maven URL
          GITHUB_REPO="${{ github.repository }}"
          JAR_FILE=$(find target -name "*.jar" | head -n 1)
          
          # Upload the JAR file to GitHub Packages
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -X PUT \
               -F "file=@${JAR_FILE}" \
               "https://maven.pkg.github.com/${GITHUB_REPO}/art-app/$(basename ${JAR_FILE})"

