name: CI/CD - Java Maven App 2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Job to build Maven JAR file
  maven-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Cache Maven Dependencies
      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build the JAR File
      - name: Build and Run Tests
        run: |
          mvn clean package
          mvn test

      # Ensure that the .jar file exists and upload it as an artifact
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-app-jar  # Name of the artifact
          path: target/*.jar  # Path to the built JAR

  # Job to build Docker image and push to GitHub Container Registry
  docker-build:
    runs-on: ubuntu-latest
    needs: maven-build  # This ensures the Docker job only runs after the Maven job completes successfully

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Download the JAR artifact from the maven-build job
      - name: Download JAR artifact
        uses: actions/download-artifact@v2
        with:
          name: my-app-jar  # Same name used during the artifact upload

      # Build Docker image
      - name: Build Docker image
        run: |
          # Build the Docker image using the downloaded JAR
          docker build -t my-app:local .

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      # Tag Docker image
      - name: Tag Docker image
        run: |
          docker tag my-app:local ghcr.io/${{ github.repository }}/my-app:latest

      # Push Docker image to GitHub Container Registry
      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}/my-app:latest
