name: CI/CD - Java Maven App 2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Cache Maven Dependencies
      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build the JAR File
      - name: Build and Run Tests
        run: |
          mvn clean package
          mvn test

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t my-app:local .

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Tag the Docker image
      - name: Tag Docker image
        run: |
          docker tag my-app:local ghcr.io/${{ github.repository }}/my-app:latest

      # Push Docker image to GitHub Container Registry
      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}/my-app:latest
